package tpami.basealgorithmlearning.datagathering.metaalgorithm.defaultparams;

public enum ELeakingBaselearnerEventType {
	START_CLASSIFY, STOP_CLASSIFY, START_DISTRIBUTION, STOP_DISTRIBUTION, START_DISTRIBUTIONS, STOP_DISTRIBUTIONS, START_BUILD_CLASSIFIER, STOP_BUILD_CLASSIFIER, START_METAFEATURE_COMPUTATION, STOP_METAFEATURE_COMPUTATION, EXCEPTION
}
